#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

if [ ! -e _common.sh ]; then
	# Get the _common.sh file if it's not in the current directory
	cp ../settings/scripts/_common.sh ./_common.sh
	chmod a+rx _common.sh
fi
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
path_url=$(ynh_app_setting_get $app path)
final_path=$(ynh_app_setting_get $app final_path)
sql=$(ynh_app_setting_get $app sql)

#=================================================
# CHECK IF THE APP CAN BE RESTORED
#=================================================

ynh_webpath_available $domain $path_url \
	|| ynh_die "Path not available: ${domain}${path_url}"
test ! -d $final_path \
	|| ynh_die "There is already a directory: $final_path "

#=================================================
# STANDARD RESTORATION STEPS
#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================

ynh_restore_file "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
var_root=/home/yunohost.app/$app
ynh_restore_file "$final_path"
ynh_restore_file "$var_root"

#=================================================
# CREATE A SQL BDD
#=================================================

if [ $sql -eq 1 ]
then
	db_name=$(ynh_sanitize_dbid $appname)db
	db_user=$(ynh_sanitize_dbid $appname)dbuser
	ynh_app_setting_set $app db_name $db_name
	ynh_mysql_setup_db $db_user $db_name
	echo "DB_NAME= $db_name" | tee "$final_path/db_info.txt"
	echo "DB_USER= $db_user" | tee -a "$final_path/db_info.txt"
	echo "DB_PASSWORD= $db_pwd" | tee -a "$final_path/db_info.txt"
	echo "DB_HOST= localhost" | tee -a "$final_path/db_info.txt"
fi


#=================================================
# RESTORE THE sql DATABASE
#=================================================
ynh_sql_execute_file_as_root ./db.sql "$db_name"

#=================================================
# RECREATE THE DEDICATED USER
#=================================================

# Create the dedicated user (if not existing)
ynh_system_user_create $app

#=================================================
# RESTORE USER RIGHTS
#=================================================

# Restore permissions on app files
chown -R $app: $final_path
chown -R root: $final_path/config.php
mkdir -p $var_root
chown -R $app:root $var_root
chmod -R 700 $var_root

#=================================================
# RESTORE THE PHP-FPM CONFIGURATION
#=================================================

ynh_restore_file "/etc/php/7.1/pool.d/$app.conf"
ynh_restore_file "/etc/php/7.1/conf.d/20-$app.ini"

#=================================================
# SPECIFIC RESTORATION
#=================================================
# REINSTALL DEPENDENCIES
#=================================================

# Define and install dependencies
ynh_install_php7

#=================================================
# RESTORE THE CRON FILE
#=================================================

ynh_restore_file "/etc/cron.d/$app"

#=================================================
# RESTORE THE LOGROTATE CONFIGURATION
#=================================================

ynh_restore_file "/etc/logrotate.d/$app"

#=================================================
# GENERIC FINALIZATION
#=================================================
# RELOAD NGINX AND PHP-FPM
#=================================================

systemctl reload php7.1-fpm
systemctl reload nginx
